### PR TITLE
created a job market candidates page

### PR DESCRIPTION
**Pull request by ernbilen**
created a page for job market candidates and added a box for the page on index.html

### CODE REVIEW

**Comment by jdebacker** [comment]
Preview from [https://htmlpreview.github.io](https://htmlpreview.github.io):

[Home page](http://htmlpreview.github.io/?https://github.com/ernbilen/UofSCEcon.github.io/blob/master/index.html)

[Job Market Candidates page](http://htmlpreview.github.io/?https://github.com/ernbilen/UofSCEcon.github.io/blob/master/job_market_candidates.html)

**Comment by jdebacker** [comment]
@ernbilen I created previews - see my previous comment.  Things look good.  Let me know when you are finished and I'll give it a final review and merge it in.

**Comment by jdebacker** [comment]
@ernbilen Let me know if you are finished here and I'll merge in your changes.  Thanks!

**Comment by ernbilen** [comment]
@jdebacker I think it should be good! Thanks so much!

**Pull request merged**
